version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      dev-deps:
        patterns:
          - "ruff"
          - "mypy"
          - "pytest*"
          - "pre-commit"
      core-deps:
        patterns:
          - "typer"
          - "rich"
          - "pyyaml"
          - "pydantic"
          - "jsonschema"
          - "httpx"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
