"""Markdown report generation."""

from __future__ import annotations

from typing import Any


def generate_report(
    project_name: str,
    results: list[dict[str, Any]],
    diff_results: list[dict[str, Any]] | None = None,
) -> str:
    """Generate a Markdown test report.

    Args:
        project_name: Name of the project.
        results: List of test result dicts.
        diff_results: Optional list of diff result dicts.

    Returns:
        Markdown formatted string.
    """
    total = len(results)
    passed = sum(1 for r in results if r.get("passed", False))
    failed = total - passed

    lines = [
        f"# a2a-spec Report: {project_name}",
        "",
        f"**{passed}/{total} passed** | {failed} failed",
        "",
    ]

    if failed > 0:
        lines.append("## ❌ Failures")
        lines.append("")
        for r in results:
            if not r.get("passed", False):
                lines.append(f"### {r['spec_name']} / {r['scenario']}")
                for error in r.get("errors", []):
                    lines.append(f"- {error}")
                lines.append("")

    if diff_results:
        lines.append("## ⚠️ Semantic Drift")
        lines.append("")
        for d in diff_results:
            severity = d.get("severity", "unknown")
            lines.append(f"- **{d['field']}**: {severity} — {d.get('explanation', '')}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [a2a-spec](https://github.com/yourorg/a2a-spec)*")

    return "\n".join(lines)
